"""add resource utilization history tables

Revision ID: 4da4bef9b8a4
Revises: a28aae90b202
Create Date: 2026-08-16 21:40:24.750647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da4bef9b8a4'
down_revision: Union[str, Sequence[str], None] = 'a28aae90b202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_utilization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilization_number', sa.String(length=20), nullable=False),
    sa.Column('production_cycle_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_cycle_id'], ['production_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_utilization_runs_id'), 'resource_utilization_runs', ['id'], unique=False)
    op.create_index(op.f('ix_resource_utilization_runs_production_cycle_id'), 'resource_utilization_runs', ['production_cycle_id'], unique=False)
    op.create_index(op.f('ix_resource_utilization_runs_utilization_number'), 'resource_utilization_runs', ['utilization_number'], unique=True)
    op.create_table('resource_utilization_history_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilization_run_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('consumed_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('remaining_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('utilization_rate', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utilization_run_id'], ['resource_utilization_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_utilization_history_items_id'), 'resource_utilization_history_items', ['id'], unique=False)
    op.create_index(op.f('ix_resource_utilization_history_items_resource_id'), 'resource_utilization_history_items', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_utilization_history_items_utilization_run_id'), 'resource_utilization_history_items', ['utilization_run_id'], unique=False)
    # ### end Alembic commands ###

    # NOTE: autogenerate also detected pre-existing drift, unrelated
    # to this migration, on cycle_resources.unit_price and three
    # sales_transactions Numeric columns (precision 4 vs 2 decimal
    # places) - the exact same drift already called out (and left
    # untouched) in 5a55db5192e6_add_users_table.py. Still predates
    # this migration and is still out of scope here; the generated
    # alter_column statements for those columns were removed from
    # both upgrade() and downgrade() below.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_utilization_history_items_utilization_run_id'), table_name='resource_utilization_history_items')
    op.drop_index(op.f('ix_resource_utilization_history_items_resource_id'), table_name='resource_utilization_history_items')
    op.drop_index(op.f('ix_resource_utilization_history_items_id'), table_name='resource_utilization_history_items')
    op.drop_table('resource_utilization_history_items')
    op.drop_index(op.f('ix_resource_utilization_runs_utilization_number'), table_name='resource_utilization_runs')
    op.drop_index(op.f('ix_resource_utilization_runs_production_cycle_id'), table_name='resource_utilization_runs')
    op.drop_index(op.f('ix_resource_utilization_runs_id'), table_name='resource_utilization_runs')
    op.drop_table('resource_utilization_runs')
    # ### end Alembic commands ###
