"""create core database tables

Revision ID: 5bf105d35a96
Revises: 
Create Date: 2026-08-09 17:15:39.756941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf105d35a96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_cycles_id'), 'production_cycles', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('cycle_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_cycle_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['production_cycle_id'], ['production_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_cycle_id', 'resource_id', name='uq_cycle_resource')
    )
    op.create_index(op.f('ix_cycle_resources_id'), 'cycle_resources', ['id'], unique=False)
    op.create_index(op.f('ix_cycle_resources_production_cycle_id'), 'cycle_resources', ['production_cycle_id'], unique=False)
    op.create_index(op.f('ix_cycle_resources_resource_id'), 'cycle_resources', ['resource_id'], unique=False)
    op.create_table('product_resource_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'resource_id', name='uq_product_resource_requirement')
    )
    op.create_index(op.f('ix_product_resource_requirements_id'), 'product_resource_requirements', ['id'], unique=False)
    op.create_index(op.f('ix_product_resource_requirements_product_id'), 'product_resource_requirements', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_resource_requirements_resource_id'), 'product_resource_requirements', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_resource_requirements_resource_id'), table_name='product_resource_requirements')
    op.drop_index(op.f('ix_product_resource_requirements_product_id'), table_name='product_resource_requirements')
    op.drop_index(op.f('ix_product_resource_requirements_id'), table_name='product_resource_requirements')
    op.drop_table('product_resource_requirements')
    op.drop_index(op.f('ix_cycle_resources_resource_id'), table_name='cycle_resources')
    op.drop_index(op.f('ix_cycle_resources_production_cycle_id'), table_name='cycle_resources')
    op.drop_index(op.f('ix_cycle_resources_id'), table_name='cycle_resources')
    op.drop_table('cycle_resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_production_cycles_id'), table_name='production_cycles')
    op.drop_table('production_cycles')
    # ### end Alembic commands ###
