"""add sales transactions

Revision ID: 7fe7eeac7b16
Revises: 8950ee100b17
Create Date: 2026-08-10 19:55:07.864433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe7eeac7b16'
down_revision: Union[str, Sequence[str], None] = '8950ee100b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_profit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_transactions_id'), 'sales_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_sales_transactions_product_id'), 'sales_transactions', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_transactions_product_id'), table_name='sales_transactions')
    op.drop_index(op.f('ix_sales_transactions_id'), table_name='sales_transactions')
    op.drop_table('sales_transactions')
    # ### end Alembic commands ###
