"""add production allocations

Revision ID: 80561256f2fc
Revises: 5bf105d35a96
Create Date: 2026-08-09 18:57:24.950800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80561256f2fc'
down_revision: Union[str, Sequence[str], None] = '5bf105d35a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_cycle_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_cycle_id'], ['production_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_cycle_id', 'product_id', name='uq_production_allocation')
    )
    op.create_index(op.f('ix_production_allocations_id'), 'production_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_production_allocations_product_id'), 'production_allocations', ['product_id'], unique=False)
    op.create_index(op.f('ix_production_allocations_production_cycle_id'), 'production_allocations', ['production_cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_allocations_production_cycle_id'), table_name='production_allocations')
    op.drop_index(op.f('ix_production_allocations_product_id'), table_name='production_allocations')
    op.drop_index(op.f('ix_production_allocations_id'), table_name='production_allocations')
    op.drop_table('production_allocations')
    # ### end Alembic commands ###
