"""add optimization history

Revision ID: 8950ee100b17
Revises: 80561256f2fc
Create Date: 2026-08-10 18:13:08.695707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8950ee100b17'
down_revision: Union[str, Sequence[str], None] = '80561256f2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_cycle_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('objective_value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['production_cycle_id'], ['production_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_runs_production_cycle_id'), 'optimization_runs', ['production_cycle_id'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimization_run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('recommended_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_profit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_results_id'), 'optimization_results', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_results_optimization_run_id'), 'optimization_results', ['optimization_run_id'], unique=False)
    op.create_index(op.f('ix_optimization_results_product_id'), 'optimization_results', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimization_results_product_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_optimization_run_id'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_id'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_optimization_runs_production_cycle_id'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    # ### end Alembic commands ###
