"""add forecast history

Revision ID: c9d7150a19d7
Revises: 7fe7eeac7b16
Create Date: 2026-08-10 20:28:36.771072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d7150a19d7'
down_revision: Union[str, Sequence[str], None] = '7fe7eeac7b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_period', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_runs_id'), 'forecast_runs', ['id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('historical_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('forecast_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('trend', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_results_forecast_run_id'), 'forecast_results', ['forecast_run_id'], unique=False)
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_results_product_id'), 'forecast_results', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_results_product_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_index(op.f('ix_forecast_results_forecast_run_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_forecast_runs_id'), table_name='forecast_runs')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
